<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Teste AdOpt</title>

  <!-- CÓDIGO DO ADOPT -->
  <meta name="adopt-website-id" content="e401acaf-7331-4681-ac2b-f3b79a4f1bba" />
  <script src="//tag.goadopt.io/injector.js?website_code=e401acaf-7331-4681-ac2b-f3b79a4f1bba" 
  class="adopt-injector"></script>
</head>
<body>
  <h1>Site de Teste - AdOpt</h1>
  <p>Se tudo estiver certo, o banner de cookies aparecerá abaixo.</p>
</body>
</html>
